{% set name = "pyIGRF" %}
{% set version = "0.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "5317099441f46919572232784b1170205ef95759962be1511e3644246fe398b9"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - numpy
    - python

test:
  imports:
    - pyIGRF

about:
  home: "https://github.com/zzyztyy/pyIGRF"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "IGRF-12 Model by Python"
  dev_url: "https://github.com/zzyztyy/pyIGRF"

extra:
  recipe-maintainers:
    - jordan-heemskerk
