{% set name = "pyIGRF" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: d117a33a8ee5a31aeae415fe9a6777a6586e7ee54184fc74d84df20bb75ebd81

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - numpy
    - python

test:
  imports:
    - pyIGRF

about:
  home: https://github.com/zzyztyy/pyIGRF
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: IGRF-12 Model by Python
  dev_url: https://github.com/zzyztyy/pyIGRF

extra:
  recipe-maintainers:
    - jordan-heemskerk
